# Generated by Django 5.1.2 on 2024-10-27 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0002_alter_cliente_cpf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='cpf',
            new_name='CPF',
        ),
    ]
