# Generated by Django 5.1.2 on 2024-10-30 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0003_rename_cpf_cliente_cpf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='CPF',
            new_name='cpf',
        ),
    ]
